#define brel_Tmatrice    _DLL_call (short      ,(short),                               0)
#define Nova0Matrica     _DLL_call (Matrica *  ,(short,short),                         1)
#define M_brisi          _DLL_call (void       ,(Matrica *),                           2)
#define MatKrut_EIc      _DLL_call (MatricaGT *,(Duz*,float,BOOL,Materijal*,PopPres*), 3)
#define MatKrut_promPP   _DLL_call (MatricaGT *,(short,float *,float),                 4)
#define MatTransf        _DLL_call (Matrica *  ,(Duz*,BOOL),                           5)
#define mnozi_M          _DLL_call (Matrica *  ,(Matrica*,Matrica*),                   6)
#define mnozi_M_skalarom _DLL_call (Matrica *  ,(Matrica*,float),                      7)
#define mnozi_GTM_M      _DLL_call (Matrica *  ,(MatricaGT*,Matrica*),                 8)
#define matrici_dodeli_vr_druge _DLL_call (void,(Matrica*,  Matrica*),                 9)
#define NovaTransp_M     _DLL_call (Matrica *  ,(Matrica*),                           10)
#define InverznaMatrica  _DLL_call (Matrica *  ,(Matrica*),                           11)
#define Matrica_u_Matrix _DLL_call (float  **  ,(Matrica*),                           12)
#define Matrix_u_Matrica _DLL_call (Matrica *  ,(float**,  short,short),              13)
#define Matrix_nova      _DLL_call (float  **  ,(short),                              14)
#define MatrixInversion  _DLL_call (void       ,(float **,  int,  float **),          15)
#define ieM              _DLL_call (short      ,(short,     short,short),             16)
#define ieGTM            _DLL_call (short      ,(short,     short,short),             17)
#define eM               _DLL_call (float *    ,(Matrica*,  short,short),             18)
#define eGTM             _DLL_call (float *    ,(MatricaGT*,short,short),             19)
#define GTMuM            _DLL_call (Matrica *  ,(MatricaGT*),                         20)
#define Izbaci_VrKol_IzMatGT _DLL_call (MatricaGT *,(MatricaGT *,short,short *,short),21)
#define Izbaci_VrKol_IzMat   _DLL_call (Matrica *,  (Matrica   *,short,short *,short),22)
#define ZanemariNsilu_K  _DLL_call (void       ,(MatricaGT **,short),                 23)
#define ZanemariNsilu_TC _DLL_call (void       ,(Matrica   **,short,BOOL),            24)
#define ElementiFo       _DLL_call (float*,     (Duz *,SlozeniStap *,PopPres *,short),25)
#define KonstanteStapaPromPP   _DLL_call (float *,(short, float *),                   26)
#define Prr_KonstStapaPromPP   _DLL_call (void   ,(short, float *, float *, WINDOW *),27)
#define MatricaRavnoteze _DLL_call (Matrica *    ,(Duz *, float),                     28)
#define IzveziMatricu    _DLL_call (BOOL         ,(Matrica *,   const char *),        29)
#define IzveziMatricuGT  _DLL_call (BOOL         ,(MatricaGT *, const char *),        30)
#define NovaTMatrica     _DLL_call (MatricaGT *  ,(short n),                          31)
#define MatKrutKnn_Prr   _DLL_call (MatricaGT *  ,(MatricaGT *,short,BOOL *,char ***),32)
#define ZanemariNsilu_T  _DLL_call (void         ,(Matrica **, short,BOOL)           ,33)
#define MatKrutLok_Prr   _DLL_call (MatricaGT *  ,(Duz *, BOOL, float **,float **, Materijal *,PopPres *,SlozeniStap *, short ,short),34)
#define MatKrutGlob_Prr  _DLL_call (Matrica *,    (Duz *, BOOL ,Materijal *,PopPres *,SlozeniStap *,short,short,short,float[3]),35)
#define MatKrutNosaca_Prr _DLL_call (MatricaGT *, (Duz *, Tacka *, short, BOOL,Materijal *,PopPres *,SlozeniStap *,short,short,GrUslovi *,short,float[3]),36)
#define Mat_Zameni_Vr_ili_Kol _DLL_call (void,    (Matrica *,short i[2],short)       ,37)
#define Mat_LinKombinuj_vk _DLL_call (void,       (Matrica *,short i[2],short koef[2],short ),38)
#define superpozicija_XiMi _DLL_call (void       ,(float *, Duz *, short),            39)
//#define StampajMatricu     _DLL_call (void       ,(Matrica *M,char **zaglavlje),      40)
#define tabela             _DLL_call  (OperacijaTab *,(FrmtTab *ft),                  40)
#define MatK_stabilnost    _DLL_call  (MatricaGT *, (Duz * d,float Ic,float lc,PopPres *ppres),    41)
#define MatKg_stabilnost   _DLL_call  (MatricaGT *, (Duz * d,         float lc,float Pc),          42)